# Dynamic port configuration override
# This file is used when ports need to be changed due to conflicts

services:
  frontend:
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:${BACKEND_PORT:-8005}/api/v1
      - PORT=3000

  api:
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - DATABASE_URL=postgresql://docuser:docpass@postgres:5432/docprocessor
      - REDIS_URL=redis://redis:6379

  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"

  nginx:
    ports:
      - "${NGINX_PORT:-80}:80"