"""Add job_id to documents table

Revision ID: 36003403b77b
Revises: 
Create Date: 2025-05-24 13:03:48.318490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36003403b77b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('job_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_documents_job_id'), 'documents', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_job_id'), table_name='documents')
    op.drop_column('documents', 'job_id')
    # ### end Alembic commands ###
